Repository phosmobile-technologies/credit-business-management-app-api, pull requests merged in 2020-03, with the labels that each got.

#58 Feature/56/customer wallet
  app/Models/UserPermissions.php
  app/Models/Wallet.php
  app/Models/enums/ContributionType.php
  app/Models/enums/TransactionOwnerType.php
  app/Models/enums/TransactionType.php
  app/Policies/WalletPolicy.php
  app/Providers/AppServiceProvider.php
  app/Providers/AuthServiceProvider.php
  app/Repositories/ContributionRepository.php
  app/Repositories/Interfaces/ContributionRepositoryInterface.php
  app/Repositories/Interfaces/UserRepositoryInterface.php
  app/Repositories/Interfaces/WalletRepositoryInterface.php
  app/Repositories/UserRepository.php
  app/Repositories/WalletRepository.php
  app/Services/TransactionService.php
  app/Services/UserService.php
  app/Services/WalletService.php
  app/User.php
  database/factories/ContributionPlanFactory.php
  database/factories/TransactionFactory.php
  database/factories/WalletFactory.php
  database/migrations/2020_01_13_133211_create_contribution_plans_table.php
  database/migrations/2020_01_14_081717_create_transactions_table.php
  database/migrations/2020_02_24_142411_create_wallets_table.php
  database/seeds/DatabaseSeeder.php
  database/seeds/RolesAndPermissionsSeeder.php
  database/seeds/TransactionsTableSeeder.php
  database/seeds/WalletTableSeeder.php
  graphql/models/ContributionPlan.graphql
  graphql/models/Transaction.graphql
  graphql/models/User.graphql
  graphql/models/Wallet.graphql
  graphql/queries/wallets.graphql
  tests/GraphQL/Helpers/Schema/WalletQueriesAndMutations.php
  tests/GraphQL/Helpers/Traits/InteractsWithTestUsers.php
  tests/GraphQL/Helpers/Traits/InteractsWithTestWallets.php
  tests/GraphQL/UserRegistrationTest.php
  tests/GraphQL/WalletPaymentTransactionsTest.php
  tests/GraphQL/WalletQueriesTest.php
  tests/GraphQL/WalletWithdrawalTransactionsTest.php
  tests/Unit/Services/UserServiceTest.php
Labels: enhancement

#63 [feature/60/create-Contribution-mutation-bug] default values are set …
  app/Services/ContributionService.php
  database/factories/ContributionPlanFactory.php
  database/migrations/2020_01_13_133211_create_contribution_plans_table.php
Labels: bug

#70 [feature/67/userprofile-bug] fixes bugs on UserProfile and runs a 'register user' test
  database/factories/UserProfileFactory.php
  database/migrations/2019_11_13_073940_create_user_profile_table.php
  graphql/auth.graphql
  graphql/models/UserProfile.graphql
  tests/GraphQL/UserRegistrationTest.php
Labels: bug

#72 Users(CUSTOMER) can still be created by the admin
  app/Events/NewUserRegistered.php
  app/Listeners/SendUserRegistrationEmail.php
  app/Mail/NewUserRegisteredMail.php
  app/Models/enums/RegistrationSource.php
  app/Repositories/Interfaces/UserRepositoryInterface.php
  app/Repositories/UserRepository.php
  app/Services/UserService.php
  app/User.php
  database/factories/UserProfileFactory.php
  database/migrations/2019_11_13_073940_create_user_profile_table.php
  graphql/auth.graphql
  graphql/models/UserProfile.graphql
  resources/views/email/signup/user.blade.php
  tests/Unit/Services/UserServiceTest.php
Labels: enhancement

#78 Feature/74/get company branches query
  graphql/models/UserProfile.graphql
  graphql/queries/companies.graphql
  tests/GraphQL/BranchQueriesTest.php
  tests/GraphQL/Helpers/Schema/BranchQueriesAndMutations.php
Labels: feature

#79 removed auth header from GetCompany Query so unauthenticated user can…
  graphql/queries/companies.graphql
Labels: feature

#81 modify contributions models
  database/factories/ContributionPlanFactory.php
  database/migrations/2020_01_13_133211_create_contribution_plans_table.php
  graphql/inputs/contribution-inputs.graphql
  graphql/models/ContributionPlan.graphql
Labels: enhancement

#87 modified new contribution inputs
  graphql/inputs/contribution-inputs.graphql
  graphql/models/ContributionPlan.graphql
  tests/GraphQL/ContributionMutationsTest.php
Labels: bug

#93 Feature/84/cash movement between wallets and contribution plans
  app/GraphQL/Mutations/FundContributionPlanFromWallet.php
  app/GraphQL/Mutations/WithdrawFromContributionPlanToWallet.php
  app/Models/enums/TransactionType.php
  app/Policies/ContributionPlanPolicy.php
  app/Repositories/ContributionRepository.php
  app/Repositories/Interfaces/ContributionRepositoryInterface.php
  app/Services/ContributionService.php
  app/Services/TransactionService.php
  app/Services/WalletService.php
  database/migrations/2020_01_14_081717_create_transactions_table.php
  graphql/inputs/contribution-inputs.graphql
  graphql/mutations/contribution-mutations.graphql
  tests/GraphQL/Helpers/Schema/ContributionQueriesAndMutations.php
  tests/GraphQL/Helpers/Traits/InteractsWithGraphQLRequests.php
  tests/GraphQL/Helpers/Traits/InteractsWithTestWallets.php
  tests/GraphQL/Helpers/storage/oauth-private.key
  tests/GraphQL/Helpers/storage/oauth-public.key
  tests/GraphQL/Mutations/FundContributionPlanFromWalletTest.php
  tests/GraphQL/Mutations/WithdrawFromContributionPlanToWalletTest.php
Labels: enhancement
